import {
  BriefcaseBusiness,
  Database,
  FolderKanban,
  GraduationCap,
  HeartPulse,
  Lightbulb,
  LockKeyhole,
  RefreshCw,
  Sparkles,
  WalletCards,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import { ChartCard } from "@/components/common/chart-card";
import { PageHeader } from "@/components/common/page-header";
import { SectionCard } from "@/components/common/section-card";
import { StatusBadge } from "@/components/common/status-badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { insightsService } from "@/services/insights";
import type {
  DashboardInsight,
  FutureAgent,
  InsightDomain,
  InsightTrendPoint,
} from "@/types/insights";

type DomainFilter = InsightDomain | "all";

const domainIcons = {
  finance: WalletCards,
  health: HeartPulse,
  learning: GraduationCap,
  career: BriefcaseBusiness,
  projects: FolderKanban,
} satisfies Record<InsightDomain, typeof WalletCards>;

const filterLabels: { id: DomainFilter; label: string }[] = [
  { id: "all", label: "All" },
  { id: "finance", label: "Finance" },
  { id: "health", label: "Health" },
  { id: "learning", label: "Learning" },
  { id: "career", label: "Career" },
  { id: "projects", label: "Projects" },
];

export function InsightsPage() {
  const [insights, setInsights] = useState<DashboardInsight[]>([]);
  const [trend, setTrend] = useState<InsightTrendPoint[]>([]);
  const [agents, setAgents] = useState<FutureAgent[]>([]);
  const [filter, setFilter] = useState<DomainFilter>("all");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const loadInsights = () => {
    setLoading(true);
    setError(false);
    Promise.all([
      insightsService.getInsights(),
      insightsService.getTrend(),
      insightsService.getFutureAgents(),
    ])
      .then(([insightData, trendData, agentData]) => {
        setInsights(insightData);
        setTrend(trendData);
        setAgents(agentData);
      })
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadInsights();
  }, []);

  const visibleInsights = useMemo(
    () =>
      insights.filter(
        (insight) => filter === "all" || insight.domain === filter,
      ),
    [filter, insights],
  );

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Cross-domain signals"
        title="Insights"
        description="Patterns derived from the information already visible across your dashboard."
      />

      <div className="flex items-start gap-3 rounded-2xl border border-primary/20 bg-primary/[0.07] p-4 sm:p-5">
        <span className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary">
          <Database className="size-4" />
        </span>
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold">Mock-data insights</p>
            <StatusBadge tone="info">Phase 1</StatusBadge>
          </div>
          <p className="mt-1.5 max-w-3xl text-sm leading-6 text-muted-foreground">
            These observations are deterministic examples derived from local
            mock records. They are not generated by AI, financial advice, or
            medical guidance.
          </p>
        </div>
      </div>

      {loading ? (
        <div className="grid gap-4 lg:grid-cols-2">
          {Array.from({ length: 4 }, (_, index) => (
            <Skeleton key={index} className="h-48 rounded-2xl" />
          ))}
        </div>
      ) : error ? (
        <SectionCard>
          <div className="py-12 text-center">
            <Lightbulb className="mx-auto size-8 text-muted-foreground" />
            <p className="mt-4 text-sm text-muted-foreground">
              The insight set could not be loaded.
            </p>
            <Button className="mt-4" variant="outline" onClick={loadInsights}>
              <RefreshCw /> Try again
            </Button>
          </div>
        </SectionCard>
      ) : (
        <>
          <div
            className="flex gap-2 overflow-x-auto pb-1"
            aria-label="Filter insights by domain"
          >
            {filterLabels.map((item) => (
              <Button
                key={item.id}
                size="sm"
                variant={filter === item.id ? "secondary" : "ghost"}
                onClick={() => setFilter(item.id)}
                aria-pressed={filter === item.id}
              >
                {item.label}
              </Button>
            ))}
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            {visibleInsights.map((insight) => {
              const Icon = domainIcons[insight.domain];
              return (
                <article
                  key={insight.id}
                  className="group rounded-2xl border border-border bg-card/70 p-5 shadow-panel transition hover:-translate-y-0.5 hover:border-white/15"
                >
                  <div className="flex items-start justify-between gap-4">
                    <span className="flex size-10 items-center justify-center rounded-xl bg-secondary text-muted-foreground transition group-hover:bg-primary/10 group-hover:text-primary">
                      <Icon className="size-4.5" />
                    </span>
                    <div className="text-right">
                      <p className="font-display text-2xl font-semibold tracking-tight">
                        {insight.metric}
                      </p>
                      <p className="text-[11px] text-muted-foreground">
                        {insight.comparison}
                      </p>
                    </div>
                  </div>
                  <div className="mt-5 flex flex-wrap items-center gap-2">
                    <StatusBadge
                      tone={
                        insight.sentiment === "positive"
                          ? "success"
                          : insight.sentiment === "attention"
                            ? "warning"
                            : "neutral"
                      }
                    >
                      {insight.sentiment}
                    </StatusBadge>
                    <span className="text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
                      {insight.domain}
                    </span>
                  </div>
                  <h2 className="mt-3 font-display text-lg font-semibold tracking-tight">
                    {insight.title}
                  </h2>
                  <p className="mt-2 text-sm leading-6 text-muted-foreground">
                    {insight.summary}
                  </p>
                  <p className="mt-4 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">
                    <span className="font-medium text-foreground">
                      Evidence:
                    </span>{" "}
                    {insight.evidence}
                  </p>
                </article>
              );
            })}
          </div>

          <ChartCard
            title="Personal operating rhythm"
            description="Six-month mock index for consistency and cross-domain balance."
            height={300}
          >
            <ResponsiveContainer width="100%" height="100%">
              <LineChart
                data={trend}
                margin={{ top: 12, right: 12, left: -18, bottom: 0 }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  vertical={false}
                  stroke="hsl(var(--border))"
                />
                <XAxis
                  dataKey="label"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "hsl(var(--muted-foreground))", fontSize: 12 }}
                />
                <YAxis
                  domain={[40, 100]}
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "hsl(var(--muted-foreground))", fontSize: 12 }}
                />
                <Tooltip
                  contentStyle={{
                    background: "hsl(var(--popover))",
                    border: "1px solid hsl(var(--border))",
                    borderRadius: 12,
                    fontSize: 12,
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="consistency"
                  name="Consistency"
                  stroke="hsl(var(--primary))"
                  strokeWidth={2.5}
                  dot={false}
                  activeDot={{ r: 4 }}
                />
                <Line
                  type="monotone"
                  dataKey="balance"
                  name="Balance"
                  stroke="hsl(var(--success))"
                  strokeWidth={2}
                  dot={false}
                  activeDot={{ r: 4 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </ChartCard>

          <SectionCard
            title="Specialist agents"
            description="Future permissioned assistants will work through the same domain service boundaries."
            action={<StatusBadge tone="neutral">Coming later</StatusBadge>}
          >
            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
              {agents.map((agent) => (
                <article
                  key={agent.id}
                  className="relative overflow-hidden rounded-xl border border-border bg-background/35 p-4"
                >
                  <div className="flex items-center justify-between gap-3">
                    <span className="flex size-9 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
                      <Sparkles className="size-4" />
                    </span>
                    <LockKeyhole
                      className="size-3.5 text-muted-foreground"
                      aria-label="Not available in Phase 1"
                    />
                  </div>
                  <h3 className="mt-4 text-sm font-semibold">{agent.name}</h3>
                  <p className="mt-2 text-xs leading-5 text-muted-foreground">
                    {agent.description}
                  </p>
                </article>
              ))}
            </div>
          </SectionCard>
        </>
      )}
    </div>
  );
}

export default InsightsPage;
